# Generated by Django 5.2.4 on 2025-08-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='usr_from',
            new_name='user_from',
        ),
    ]
